name: Deploy to Shoper via WebDAV

on:
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Deploy to WebDAV
        env:
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            npm run deploy:develop
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            npm run deploy:staging
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; thenF
            npm run deploy:production
          fi
